import type { Locale } from "@/lib/i18n/config";

export const APP_FLOW_COPY = {
  en: {
    generator: {
      title: "Instant AI Training Plan Generator",
      subtitle: "Build a structured training plan from your goal, schedule, and target muscles.",
      coachCta: "Prefer a coach-built plan?",
      cardTitle: "Generator",
      requiredInputs: "Required inputs",
      duration: "Program Duration (1-12 weeks)",
      frequency: "Training Frequency (2-6 sessions/week)",
      week: "week",
      weeks: "weeks",
      sessions: "sessions",
      gender: "Gender",
      male: "Male",
      female: "Female",
      workoutTypes: "Workout Types",
      targetMuscles: "Target Muscle Groups",
      selected: (count: number) => `Selected (${count})`,
      workoutSearch: "Search workout types...",
      muscleSearch: "Search muscle groups...",
      strength: "Strength",
      home: "Home",
      mobility: "Mobility",
      clear: "Clear",
      noWorkoutTypes: "No workout types found",
      noMuscles: "No muscle groups found",
      selectGender: "Select gender",
      selectWorkoutType: "Select at least one workout type",
      selectTargetMuscle: "Select at least one target muscle",
      error: "Error",
      success: "Success",
      dismiss: "Dismiss",
      costBreakdown: "Cost Breakdown",
      yourBalance: "Your balance",
      previewCost: "Preview cost",
      fullPlanCost: "Full plan cost",
      affectsPrice: "What affects the price",
      baseCost: (weeks: number, sessions: number) => `Base cost (${weeks} weeks × ${sessions} sessions)`,
      workoutTypesSelected: (count: number) => `Workout types (${count} selected)`,
      targetMusclesSelected: (count: number) => `Target muscles (${count} selected)`,
      injurySafe: "Injury-safe modifications",
      specialEquipment: "Special equipment",
      nutritionTips: "Nutrition tips",
      pdfExport: (images?: number) => `PDF export${images ? ` (${images} images)` : ""}`,
      missingRequired: "Missing required inputs",
      seePricing: "See pricing",
      signInGenerate: "Sign in to generate",
      notEnoughTokens: "Not enough tokens",
      topUpTokens: "Top up tokens",
      publishing: "Publishing...",
      fillRequired: "Fill required fields",
      insufficientTokens: (balance: number, cost: number) => `Insufficient tokens (${balance}/${cost})`,
      generatePlan: (cost: number) => `Generate Plan (${cost} tokens)`,
      regenerate: (day: number, week: number) => `Regenerate: day -${day} • week -${week}`,
      alerts: {
        insufficient: (need: number, have: number) => `Insufficient tokens. You need ${need} tokens, but have ${have}.`,
        previewFailed: "Preview failed",
        previewSuccess: "Preview generated successfully!",
        previewFallback: "Failed to generate preview",
        publishFailed: "Publish failed",
        publishSuccess: "Course published successfully!",
        publishFallback: "Failed to publish course",
      },
    },
    dashboard: {
      signInRequired: "Sign in required",
      signInRequiredBody: "Please sign in to view your dashboard, courses, and token history.",
      signIn: "Sign in",
      wallet: "Wallet",
      refreshBalance: "Refresh balance",
      tokens: "tokens",
      coursesCreated: "Courses Created",
      totalCourses: "Total courses in your account",
      totalSpent: "Total Spent",
      tokensSpentOnCourses: "Tokens spent on courses",
      accountSettings: "Settings",
      accountSettingsBody: "Edit your profile, address, and password",
      manageAccount: "Manage account ->",
      latestPreview: "Latest Preview",
      preview: "Preview",
      generatedImages: "Generated Images:",
      publishFullCourse: "Publish Full Course",
      publishing: "Publishing...",
      failedPublish: "Failed to publish course",
      unknownError: "Unknown error",
      myBookings: "My Bookings",
      bookNewSession: "Book new session ->",
      today: "Today",
      upcoming: "Upcoming",
      noBookings: "No bookings yet",
      noBookingsBody: "Booked training sessions will appear here.",
      coachRequests: "Coach Requests",
      spent: "Spent:",
      openCourse: "Open Course",
      open: "Open",
      dismiss: "Dismiss",
      goal: "Goal:",
      daysPerWeek: "days/week",
      coachRequestPending: "Your coach has received your request. Your personalized course is being prepared.",
      downloadPdf: "Download PDF",
      generatePdf: "Generate PDF",
      generating: "Generating...",
      errorPrefix: "Error:",
      yourCourses: "Your Courses",
      exportCsv: "Export CSV",
      loadingCourses: "Loading courses...",
      noCourses: "No courses yet",
      noCoursesBody: "Generated plans and completed coach requests will appear here.",
      untitledCourse: "Untitled Course",
      regenerateDay: "Regenerate day",
      transactionHistory: "Transaction History",
      loadingTransactions: "Loading transactions...",
      noTransactions: "No transactions yet",
      noTransactionsBody: "Your token transactions will appear here.",
      loadingMore: "Loading more transactions...",
      loadMore: "Load More Transactions",
      courseDetails: "Course Details",
      created: "Created:",
      tokensSpent: "Tokens spent:",
      pdfAvailable: "PDF available",
      courseOptions: "Course Options",
      actions: "Actions",
      duration: "Duration:",
      sessions: "Sessions:",
      injurySafe: "Injury Safe:",
      equipment: "Equipment:",
      nutrition: "Nutrition:",
      images: "Images:",
      yes: "Yes",
      no: "No",
      required: "Required",
      included: "Included",
      notIncluded: "Not included",
      failedParseOptions: "Failed to parse course options",
      regenerateSpecificDay: "Regenerate Specific Day",
      week: "Week:",
      day: "Day:",
      perWeek: "/week",
      cost: "Cost:",
      sameAsFullCourse: "same as full course",
      regenerating: "Regenerating...",
      close: "Close",
      statuses: {
        pending: "Pending",
        processing: "Processing",
        done: "Done",
        failed: "Failed",
        confirmed: "Confirmed",
        cancelled: "Cancelled",
        completed: "Completed",
        topup: "Top-up",
        spend: "Spend",
      },
      alerts: {
        regenerated: (week: number, day: number, cost: string) => `Successfully regenerated Week ${week}, Day ${day}. Cost: ${cost} tokens`,
        insufficient: (required: string, balance: string) => `Insufficient tokens. Required: ${required}, Balance: ${balance}`,
        failedRegenerate: "Failed to regenerate day. Please try again.",
        failedPdfStart: "Failed to start PDF generation",
        pdfSignIn: "You need to be logged in to generate PDF. Please sign in.",
        courseNotFound: "Course not found. Please refresh the page and try again.",
        tryPdfAgain: "You can try again by clicking the Generate PDF button.",
      },
    },
    checkout: {
      title: "Checkout",
      thankYou: "Thank You!",
      securePayment: "Secure Payment",
      paymentSuccessful: "Payment successful!",
      successBody: "Your tokens have been added to your account balance. You can now use them to generate courses and access premium features.",
      redirecting: "Redirecting to dashboard...",
      orderSummary: "Order Summary",
      customTopUp: "Custom top-up",
      subtotal: "Subtotal",
      total: "Total",
      purchaseTokens: (tokens: string) => `You are purchasing ${tokens} tokens.`,
      credited: "Tokens will be credited to your account immediately after payment.",
      confirmationEmail: (email: string) => `A confirmation email will be sent to ${email}.`,
      paymentDetails: "Payment Details",
      placeholders: {
        cardNumber: "Card number",
        expiry: "MM/YY",
        cvv: "CVV",
        name: "Cardholder name",
        address: "Billing address",
        city: "City",
        postalCode: "Postal code",
      },
      errors: {
        cardNumber: "Card number must be 16 digits",
        expiry: "Format must be MM/YY",
        cvv: "CVV must be 3 digits",
        name: "Cardholder name is required",
        address: "Billing address is required",
        city: "City is required",
        postalCode: "Postal code is required",
        initFailed: "Payment initialization failed",
        failed: "Payment failed. Please try again.",
      },
      processing: "Processing...",
      signInContinue: "Please sign in to continue",
      pay: (amount: string, currency: string) => `Pay ${amount} ${currency}`,
    },
    paymentStatus: {
      loading: "Loading...",
      waiting: "Waiting for payment confirmation...",
      missingOrder: "Order ID is missing. Please retry payment from checkout.",
      statusFailed: "Status check failed",
      approved: "Payment approved. Crediting tokens...",
      processingMessage: "Payment is still processing. Please wait...",
      pollingFailed: "Payment status polling failed.",
      timedOut: "Payment confirmation timed out. Please refresh this page.",
      processingTitle: "Processing payment...",
      successTitle: "Payment successful",
      failedTitle: "Payment failed",
      tokensAdded: (tokens: string) => `${tokens} tokens added.`,
      backPricing: "Back to pricing",
      failedBody: "Unfortunately, your payment could not be processed.",
      reason: "Reason:",
      order: "Order:",
      tryAgain: "Try again",
      backHome: "Back to Home",
    },
    account: {
      title: "Account Settings",
      loadingProfile: "Loading profile...",
      personal: "Personal Information",
      firstName: "First name",
      lastName: "Last name",
      email: "Email",
      phone: "Phone number",
      dob: "Date of birth",
      address: "Address",
      street: "Street address",
      city: "City",
      postalCode: "Postal code",
      selectCountry: "Select country",
      saveChanges: "Save changes",
      profileSaved: "Profile updated successfully.",
      profileLoadFailed: "Failed to load profile",
      profileSaveFailed: "Failed to save profile",
      changePassword: "Change Password",
      currentPassword: "Current password",
      newPassword: "New password",
      confirmPassword: "Confirm new password",
      currentPasswordPlaceholder: "Enter current password",
      newPasswordPlaceholder: "At least 6 characters",
      confirmPasswordPlaceholder: "Re-enter new password",
      passwordTooShort: "New password must be at least 6 characters.",
      passwordsNoMatch: "New passwords do not match.",
      passwordChangeFailed: "Failed to change password",
      passwordChanged: "Password changed successfully.",
    },
  },
  tr: {
    generator: {
      title: "Instant AI Antrenman Planı Oluşturucu",
      subtitle: "Hedefiniz, programınız ve hedef kaslarınıza göre yapılandırılmış bir antrenman planı oluşturun.",
      coachCta: "Koç tarafından hazırlanan plan mı istersiniz?",
      cardTitle: "Oluşturucu",
      requiredInputs: "Zorunlu bilgiler",
      duration: "Program süresi (1-12 hafta)",
      frequency: "Antrenman sıklığı (haftada 2-6 seans)",
      week: "hafta",
      weeks: "hafta",
      sessions: "seans",
      gender: "Cinsiyet",
      male: "Erkek",
      female: "Kadın",
      workoutTypes: "Antrenman türleri",
      targetMuscles: "Hedef kas grupları",
      selected: (count: number) => `Seçili (${count})`,
      workoutSearch: "Antrenman türü ara...",
      muscleSearch: "Kas grubu ara...",
      strength: "Güç",
      home: "Ev",
      mobility: "Mobilite",
      clear: "Temizle",
      noWorkoutTypes: "Antrenman türü bulunamadı",
      noMuscles: "Kas grubu bulunamadı",
      selectGender: "Cinsiyet seçin",
      selectWorkoutType: "En az bir antrenman türü seçin",
      selectTargetMuscle: "En az bir hedef kas seçin",
      error: "Hata",
      success: "Başarılı",
      dismiss: "Kapat",
      costBreakdown: "Maliyet dökümü",
      yourBalance: "Bakiyeniz",
      previewCost: "Önizleme maliyeti",
      fullPlanCost: "Tam plan maliyeti",
      affectsPrice: "Fiyatı etkileyenler",
      baseCost: (weeks: number, sessions: number) => `Temel maliyet (${weeks} hafta × ${sessions} seans)`,
      workoutTypesSelected: (count: number) => `Antrenman türleri (${count} seçili)`,
      targetMusclesSelected: (count: number) => `Hedef kaslar (${count} seçili)`,
      injurySafe: "Sakatlık riskini azaltan düzenlemeler",
      specialEquipment: "Özel ekipman",
      nutritionTips: "Beslenme ipuçları",
      pdfExport: (images?: number) => `PDF çıktısı${images ? ` (${images} görsel)` : ""}`,
      missingRequired: "Eksik zorunlu bilgiler",
      seePricing: "Fiyatları gör",
      signInGenerate: "Oluşturmak için giriş yap",
      notEnoughTokens: "Yeterli token yok",
      topUpTokens: "Token yükle",
      publishing: "Yayınlanıyor...",
      fillRequired: "Zorunlu alanları doldurun",
      insufficientTokens: (balance: number, cost: number) => `Yetersiz token (${balance}/${cost})`,
      generatePlan: (cost: number) => `Plan oluştur (${cost} token)`,
      regenerate: (day: number, week: number) => `Yeniden oluşturma: gün -${day} • hafta -${week}`,
      alerts: {
        insufficient: (need: number, have: number) => `Yetersiz token. ${need} token gerekiyor, sizde ${have} var.`,
        previewFailed: "Önizleme başarısız",
        previewSuccess: "Önizleme başarıyla oluşturuldu!",
        previewFallback: "Önizleme oluşturulamadı",
        publishFailed: "Yayınlama başarısız",
        publishSuccess: "Program başarıyla yayınlandı!",
        publishFallback: "Program yayınlanamadı",
      },
    },
    dashboard: {
      signInRequired: "Giriş gerekli",
      signInRequiredBody: "Panelinizi, programlarınızı ve token geçmişinizi görmek için giriş yapın.",
      signIn: "Giriş yap",
      wallet: "Cüzdan",
      refreshBalance: "Bakiyeyi yenile",
      tokens: "token",
      coursesCreated: "Oluşturulan programlar",
      totalCourses: "Hesabınızdaki toplam program",
      totalSpent: "Toplam harcama",
      tokensSpentOnCourses: "Programlarda harcanan token",
      accountSettings: "Ayarlar",
      accountSettingsBody: "Profilinizi, adresinizi ve şifrenizi düzenleyin",
      manageAccount: "Hesabı yönet ->",
      latestPreview: "Son önizleme",
      preview: "Önizleme",
      generatedImages: "Oluşturulan görseller:",
      publishFullCourse: "Tam programı yayınla",
      publishing: "Yayınlanıyor...",
      failedPublish: "Program yayınlanamadı",
      unknownError: "Bilinmeyen hata",
      myBookings: "Rezervasyonlarım",
      bookNewSession: "Yeni seans ayırt ->",
      today: "Bugün",
      upcoming: "Yaklaşan",
      noBookings: "Henüz rezervasyon yok",
      noBookingsBody: "Rezerve edilen antrenman seansları burada görünür.",
      coachRequests: "Koç talepleri",
      spent: "Harcanan:",
      openCourse: "Programı aç",
      open: "Aç",
      dismiss: "Kapat",
      goal: "Hedef:",
      daysPerWeek: "gün/hafta",
      coachRequestPending: "Koçunuz talebinizi aldı. Kişisel programınız hazırlanıyor.",
      downloadPdf: "PDF indir",
      generatePdf: "PDF oluştur",
      generating: "Oluşturuluyor...",
      errorPrefix: "Hata:",
      yourCourses: "Programlarınız",
      exportCsv: "CSV dışa aktar",
      loadingCourses: "Programlar yükleniyor...",
      noCourses: "Henüz program yok",
      noCoursesBody: "Oluşturulan planlar ve tamamlanan koç talepleri burada görünür.",
      untitledCourse: "Adsız program",
      regenerateDay: "Günü yeniden oluştur",
      transactionHistory: "İşlem geçmişi",
      loadingTransactions: "İşlemler yükleniyor...",
      noTransactions: "Henüz işlem yok",
      noTransactionsBody: "Token işlemleriniz burada görünür.",
      loadingMore: "Daha fazla işlem yükleniyor...",
      loadMore: "Daha fazla işlem yükle",
      courseDetails: "Program detayları",
      created: "Oluşturulma:",
      tokensSpent: "Harcanan token:",
      pdfAvailable: "PDF hazır",
      courseOptions: "Program seçenekleri",
      actions: "İşlemler",
      duration: "Süre:",
      sessions: "Seans:",
      injurySafe: "Sakatlık güvenli:",
      equipment: "Ekipman:",
      nutrition: "Beslenme:",
      images: "Görseller:",
      yes: "Evet",
      no: "Hayır",
      required: "Gerekli",
      included: "Dahil",
      notIncluded: "Dahil değil",
      failedParseOptions: "Program seçenekleri okunamadı",
      regenerateSpecificDay: "Belirli günü yeniden oluştur",
      week: "Hafta:",
      day: "Gün:",
      perWeek: "/hafta",
      cost: "Maliyet:",
      sameAsFullCourse: "tam programla aynı",
      regenerating: "Yeniden oluşturuluyor...",
      close: "Kapat",
      statuses: {
        pending: "Beklemede",
        processing: "İşleniyor",
        done: "Tamamlandı",
        failed: "Başarısız",
        confirmed: "Onaylandı",
        cancelled: "İptal edildi",
        completed: "Tamamlandı",
        topup: "Yükleme",
        spend: "Harcama",
      },
      alerts: {
        regenerated: (week: number, day: number, cost: string) => `Hafta ${week}, Gün ${day} başarıyla yeniden oluşturuldu. Maliyet: ${cost} token`,
        insufficient: (required: string, balance: string) => `Yetersiz token. Gerekli: ${required}, Bakiye: ${balance}`,
        failedRegenerate: "Gün yeniden oluşturulamadı. Lütfen tekrar deneyin.",
        failedPdfStart: "PDF oluşturma başlatılamadı",
        pdfSignIn: "PDF oluşturmak için giriş yapmanız gerekir.",
        courseNotFound: "Program bulunamadı. Lütfen sayfayı yenileyip tekrar deneyin.",
        tryPdfAgain: "Generate PDF butonuna tıklayarak tekrar deneyebilirsiniz.",
      },
    },
    checkout: {
      title: "Ödeme",
      thankYou: "Teşekkürler!",
      securePayment: "Güvenli ödeme",
      paymentSuccessful: "Ödeme başarılı!",
      successBody: "Tokenlarınız hesap bakiyenize eklendi. Artık program oluşturmak ve premium özelliklere erişmek için kullanabilirsiniz.",
      redirecting: "Panele yönlendiriliyor...",
      orderSummary: "Sipariş özeti",
      customTopUp: "Özel yükleme",
      subtotal: "Ara toplam",
      total: "Toplam",
      purchaseTokens: (tokens: string) => `${tokens} token satın alıyorsunuz.`,
      credited: "Tokenlar ödeme sonrası hesabınıza hemen eklenecektir.",
      confirmationEmail: (email: string) => `Onay e-postası ${email} adresine gönderilecek.`,
      paymentDetails: "Ödeme bilgileri",
      placeholders: {
        cardNumber: "Kart numarası",
        expiry: "AA/YY",
        cvv: "CVV",
        name: "Kart üzerindeki isim",
        address: "Fatura adresi",
        city: "Şehir",
        postalCode: "Posta kodu",
      },
      errors: {
        cardNumber: "Kart numarası 16 haneli olmalıdır",
        expiry: "Format AA/YY olmalıdır",
        cvv: "CVV 3 haneli olmalıdır",
        name: "Kart üzerindeki isim zorunludur",
        address: "Fatura adresi zorunludur",
        city: "Şehir zorunludur",
        postalCode: "Posta kodu zorunludur",
        initFailed: "Ödeme başlatılamadı",
        failed: "Ödeme başarısız. Lütfen tekrar deneyin.",
      },
      processing: "İşleniyor...",
      signInContinue: "Devam etmek için giriş yapın",
      pay: (amount: string, currency: string) => `${amount} ${currency} öde`,
    },
    paymentStatus: {
      loading: "Yükleniyor...",
      waiting: "Ödeme onayı bekleniyor...",
      missingOrder: "Sipariş ID eksik. Lütfen ödemeyi checkout sayfasından tekrar deneyin.",
      statusFailed: "Durum kontrolü başarısız",
      approved: "Ödeme onaylandı. Tokenlar ekleniyor...",
      processingMessage: "Ödeme hâlâ işleniyor. Lütfen bekleyin...",
      pollingFailed: "Ödeme durumu kontrol edilemedi.",
      timedOut: "Ödeme onayı zaman aşımına uğradı. Lütfen sayfayı yenileyin.",
      processingTitle: "Ödeme işleniyor...",
      successTitle: "Ödeme başarılı",
      failedTitle: "Ödeme başarısız",
      tokensAdded: (tokens: string) => `${tokens} token eklendi.`,
      backPricing: "Fiyatlara dön",
      failedBody: "Ne yazık ki ödemeniz işlenemedi.",
      reason: "Sebep:",
      order: "Sipariş:",
      tryAgain: "Tekrar dene",
      backHome: "Ana sayfaya dön",
    },
    account: {
      title: "Hesap ayarları",
      loadingProfile: "Profil yükleniyor...",
      personal: "Kişisel bilgiler",
      firstName: "Ad",
      lastName: "Soyad",
      email: "E-posta",
      phone: "Telefon numarası",
      dob: "Doğum tarihi",
      address: "Adres",
      street: "Sokak adresi",
      city: "Şehir",
      postalCode: "Posta kodu",
      selectCountry: "Ülke seç",
      saveChanges: "Değişiklikleri kaydet",
      profileSaved: "Profil başarıyla güncellendi.",
      profileLoadFailed: "Profil yüklenemedi",
      profileSaveFailed: "Profil kaydedilemedi",
      changePassword: "Şifre değiştir",
      currentPassword: "Mevcut şifre",
      newPassword: "Yeni şifre",
      confirmPassword: "Yeni şifreyi onayla",
      currentPasswordPlaceholder: "Mevcut şifreyi girin",
      newPasswordPlaceholder: "En az 6 karakter",
      confirmPasswordPlaceholder: "Yeni şifreyi tekrar girin",
      passwordTooShort: "Yeni şifre en az 6 karakter olmalıdır.",
      passwordsNoMatch: "Yeni şifreler eşleşmiyor.",
      passwordChangeFailed: "Şifre değiştirilemedi",
      passwordChanged: "Şifre başarıyla değiştirildi.",
    },
  },
} as const;

export function getAppFlowCopy(locale: Locale) {
  return APP_FLOW_COPY[locale] ?? APP_FLOW_COPY.en;
}

export function formatTokenAmount(value: number, locale: Locale) {
  const formatted = value.toLocaleString(locale === "tr" ? "tr-TR" : "en-US");
  return locale === "tr" ? `${formatted} token` : `${formatted} tokens`;
}
