import { DEFAULT_LOCALE, isLocale, LOCALE_COOKIE_NAME, type Locale } from "@/lib/i18n/config";

type CoachLike = {
  slug: string;
  bio: string;
  specialties: string[];
  goals: string[];
  level: string;
  trainingType: string;
  focusAreas: string[];
};

const valueLabels = {
  en: {
    "Strength": "Strength",
    "Fat loss": "Fat loss",
    "Mobility": "Mobility",
    "Endurance": "Endurance",
    "Posture": "Posture",
    "Muscle gain": "Muscle gain",
    "Beginner": "Beginner",
    "Intermediate": "Intermediate",
    "Advanced": "Advanced",
    "Home": "Home",
    "Gym": "Gym",
    "Mixed": "Mixed",
    "None": "None",
    "Basic": "Basic",
    "Full gym": "Full gym",
    "Yoga Flow": "Yoga Flow",
    "Breathwork": "Breathwork",
    "Flexibility": "Flexibility",
    "Powerlifting": "Powerlifting",
    "Strength Programming": "Strength Programming",
    "Technique": "Technique",
    "Calisthenics": "Calisthenics",
    "Bodyweight Strength": "Bodyweight Strength",
    "Skill Progressions": "Skill Progressions",
    "Pilates": "Pilates",
    "Core Stability": "Core Stability",
    "HIIT": "HIIT",
    "Conditioning": "Conditioning",
    "Fat Loss Training": "Fat Loss Training",
    "Running": "Running",
    "5K–Half Marathon": "5K–Half Marathon",
    "Cycling": "Cycling",
    "Performance": "Performance",
    "Zone Training": "Zone Training",
    "Boxing Fitness": "Boxing Fitness",
    "Footwork": "Footwork",
    "Kettlebells": "Kettlebells",
    "Functional Strength": "Functional Strength",
    "Mobility Strength": "Mobility Strength",
    "Desk Worker Routines": "Desk Worker Routines",
    "Olympic Lifting": "Olympic Lifting",
    "Barbell Technique": "Barbell Technique",
    "Explosiveness": "Explosiveness",
    "Dance Cardio": "Dance Cardio",
    "Rhythm Training": "Rhythm Training",
    "Full-Body Conditioning": "Full-Body Conditioning",
    "Climbing Conditioning": "Climbing Conditioning",
    "Grip Strength": "Grip Strength",
    "Shoulder Health": "Shoulder Health",
    "Low-Impact Fitness": "Low-Impact Fitness",
    "Balance": "Balance",
    "Joint-Friendly Strength": "Joint-Friendly Strength",
    "Swimming Technique": "Swimming Technique",
    "Triathlon Support": "Triathlon Support",
    "Stress reset": "Stress reset",
    "Squat": "Squat",
    "Bench": "Bench",
    "Deadlift": "Deadlift",
    "Pull-ups": "Pull-ups",
    "Core": "Core",
    "Handstand basics": "Handstand basics",
    "Back-friendly training": "Back-friendly training",
    "Alignment": "Alignment",
    "Cardio": "Cardio",
    "Full body": "Full body",
    "Running plan": "Running plan",
    "Pacing": "Pacing",
    "Injury-prep basics": "Injury-prep basics",
    "FTP build": "FTP build",
    "Intervals": "Intervals",
    "Leg strength": "Leg strength",
    "Coordination": "Coordination",
    "Kettlebell basics": "Kettlebell basics",
    "Hinge pattern": "Hinge pattern",
    "Neck & shoulders": "Neck & shoulders",
    "Hips": "Hips",
    "Snatch": "Snatch",
    "Clean & Jerk": "Clean & Jerk",
    "Power development": "Power development",
    "Fun adherence": "Fun adherence",
    "Grip": "Grip",
    "Pull strength": "Pull strength",
    "Shoulder stability": "Shoulder stability",
    "Joint-friendly": "Joint-friendly",
    "Daily function": "Daily function",
    "Stroke efficiency": "Stroke efficiency",
    "Breathing": "Breathing",
    "Shoulder mobility": "Shoulder mobility",
  },
  tr: {
    "Strength": "Güç",
    "Fat loss": "Yağ kaybı",
    "Mobility": "Mobilite",
    "Endurance": "Dayanıklılık",
    "Posture": "Duruş",
    "Muscle gain": "Kas kazanımı",
    "Beginner": "Başlangıç",
    "Intermediate": "Orta seviye",
    "Advanced": "İleri seviye",
    "Home": "Ev",
    "Gym": "Spor salonu",
    "Mixed": "Karma",
    "None": "Yok",
    "Basic": "Temel",
    "Full gym": "Tam spor salonu",
    "Yoga Flow": "Yoga akışı",
    "Breathwork": "Nefes çalışması",
    "Flexibility": "Esneklik",
    "Powerlifting": "Powerlifting",
    "Strength Programming": "Güç programlama",
    "Technique": "Teknik",
    "Calisthenics": "Kalistenik",
    "Bodyweight Strength": "Vücut ağırlığı gücü",
    "Skill Progressions": "Beceri ilerlemeleri",
    "Pilates": "Pilates",
    "Core Stability": "Core stabilitesi",
    "HIIT": "HIIT",
    "Conditioning": "Kondisyon",
    "Fat Loss Training": "Yağ kaybı antrenmanı",
    "Running": "Koşu",
    "5K–Half Marathon": "5K–yarı maraton",
    "Cycling": "Bisiklet",
    "Performance": "Performans",
    "Zone Training": "Zone antrenmanı",
    "Boxing Fitness": "Boks fitness",
    "Footwork": "Ayak çalışması",
    "Kettlebells": "Kettlebell",
    "Functional Strength": "Fonksiyonel güç",
    "Mobility Strength": "Mobilite gücü",
    "Desk Worker Routines": "Masa başı rutinleri",
    "Olympic Lifting": "Olimpik kaldırış",
    "Barbell Technique": "Barbell tekniği",
    "Explosiveness": "Patlayıcılık",
    "Dance Cardio": "Dans kardiyo",
    "Rhythm Training": "Ritim antrenmanı",
    "Full-Body Conditioning": "Tüm vücut kondisyonu",
    "Climbing Conditioning": "Tırmanış kondisyonu",
    "Grip Strength": "Kavrama gücü",
    "Shoulder Health": "Omuz sağlığı",
    "Low-Impact Fitness": "Düşük etkili fitness",
    "Balance": "Denge",
    "Joint-Friendly Strength": "Eklem dostu güç",
    "Swimming Technique": "Yüzme tekniği",
    "Triathlon Support": "Triatlon desteği",
    "Stress reset": "Stres sıfırlama",
    "Squat": "Squat",
    "Bench": "Bench press",
    "Deadlift": "Deadlift",
    "Pull-ups": "Barfiks",
    "Core": "Core",
    "Handstand basics": "Amut temelleri",
    "Back-friendly training": "Sırt dostu antrenman",
    "Alignment": "Hizalama",
    "Cardio": "Kardiyo",
    "Full body": "Tüm vücut",
    "Running plan": "Koşu planı",
    "Pacing": "Tempo yönetimi",
    "Injury-prep basics": "Sakatlık önleme temelleri",
    "FTP build": "FTP geliştirme",
    "Intervals": "Interval",
    "Leg strength": "Bacak gücü",
    "Coordination": "Koordinasyon",
    "Kettlebell basics": "Kettlebell temelleri",
    "Hinge pattern": "Hinge paterni",
    "Neck & shoulders": "Boyun ve omuzlar",
    "Hips": "Kalçalar",
    "Snatch": "Snatch",
    "Clean & Jerk": "Clean & Jerk",
    "Power development": "Güç gelişimi",
    "Fun adherence": "Eğlenceli devamlılık",
    "Grip": "Kavrama",
    "Pull strength": "Çekiş gücü",
    "Shoulder stability": "Omuz stabilitesi",
    "Joint-friendly": "Eklem dostu",
    "Daily function": "Günlük fonksiyon",
    "Stroke efficiency": "Kulaç verimliliği",
    "Breathing": "Nefes",
    "Shoulder mobility": "Omuz mobilitesi",
  },
} as const;

const coachBioTr: Record<string, string> = {
  "maya-kalnina-yoga-flow": "Basit ve sürdürülebilir rutinler sunan vinyasa odaklı yoga koçu. Sakin yapı, net ipuçları ve gereksiz karmaşa yok.",
  "marco-rinaldi-powerlifting": "Güvenli ilerleme ve temiz tekniğe odaklanan deneyimli güç koçu. Planlar yapılandırılmış, ölçülebilir ve gerçekçidir.",
  "lena-berg-calisthenics": "Sizinle birlikte ölçeklenen vücut ağırlığı antrenmanı. Sağlam temeller, temiz ilerlemeler ve sakatlık dramı olmadan beceri çalışması.",
  "elise-dumont-pilates-core": "Core kontrolü ve hizalamaya odaklanan pilates koçu. Net seanslar, yumuşak ilerleme ve günlük duruş için daha güçlü bir temel.",
  "tomasz-nowak-hiit-conditioning": "Mantıklı toparlanma içeren yüksek yoğunluklu planlar. Kısa seanslar, net tempo ve haftadan haftaya hissedilen ilerleme.",
  "greta-silva-run-coach": "Bulunduğunuz seviyeden başlayan koşu planları. Basit tempo, akıllı yüklenme ve gerçek hayata uyan rutinler.",
  "johan-lind-cycling-performance": "Net haftalık yapıya sahip bisiklet odaklı programlama. Akıllı intervaller, toparlanma blokları ve güç desteği.",
  "nadia-kovac-boxing-fitness": "Dayanıklılık ve özgüven geliştiren boks ilhamlı fitness. Temiz drill'ler, akıllı ilerlemeler ve ego yok.",
  "alex-kent-kettlebell": "Atletik kalmanızı sağlayan kettlebell ile fonksiyonel antrenman. Güçlü temeller, temiz teknik ipuçları ve pratik seanslar.",
  "sara-van-dijk-mobility-posture": "Masa başı yaşam için mobilite ve duruş planları. Kısa rutinler, net ilerlemeler ve karmaşıklık olmadan güçlü alışkanlıklar.",
  "pavel-ivanov-olympic-lifting": "Patlayıcı güç için barbell tekniği koçu. Yapılandırılmış bloklar, teknik drill'ler ve gerçekçi ilerleme.",
  "chiara-conti-dance-cardio": "Eğlenceli ve etkili dans tabanlı kardiyo. Basit kombinasyonlar, düzenli ilerleme ve geri dönmek isteyeceğiniz rutinler.",
  "mikael-otto-climbing-conditioning": "Tırmanış odaklı güç ve stabilite. Kavrama, çekiş gücü ve omuz dostu programlama.",
  "irina-petrescu-low-impact": "Tutarlılık için tasarlanmış düşük etkili güç ve denge seansları. Yumuşak ilerleme, net ipuçları ve daha güvenli hareket alışkanlıkları.",
  "benoit-martin-swim-technique": "Net haftalık yapıya sahip yüzme tekniği ve dayanıklılık planları. Daha iyi verimlilik, daha akıcı nefes ve daha güçlü mobilite.",
};

export const COACHES_COPY = {
  en: {
    coachesList: {
      title: "Find your coach",
      subtitle: "Browse coaches by goal, style, and training type.",
      searchPlaceholder: "Search coaches or specialties",
      filtersButton: "Filters",
      sort: [
        { value: "recommended", label: "Recommended" },
        { value: "top-rated", label: "Top rated" },
        { value: "newest", label: "Newest" },
      ],
      quickFilters: [
        { label: "Strength", type: "goal", value: "Strength" },
        { label: "Fat loss", type: "goal", value: "Fat loss" },
        { label: "Mobility", type: "goal", value: "Mobility" },
        { label: "Endurance", type: "goal", value: "Endurance" },
        { label: "Posture", type: "goal", value: "Posture" },
        { label: "Home", type: "trainingType", value: "Home" },
        { label: "Gym", type: "trainingType", value: "Gym" },
      ],
      errorTitle: "Something went wrong",
      errorFallback: "Failed to load coaches",
      retry: "Retry",
      noMatchesTitle: "No matches",
      noMatchesBody: "Try clearing filters or searching by a different term.",
      clearFilters: "Clear filters",
      emptyTitle: "No coaches yet",
      emptyBody: "Want to be the first coach on the platform?",
      becomeCoach: "Become a Coach",
      ctaTitle: "Are you a coach?",
      ctaBody: "Apply to join and deliver your coaching through our platform.",
    },
    coachFilters: {
      title: "Filters",
      clear: "Clear",
      apply: "Apply",
      clearFilters: "Clear filters",
      sections: {
        goals: "Goals",
        level: "Level",
        trainingType: "Training Type",
        languages: "Languages",
        focusAreas: "Focus Areas",
      },
    },
    coachCard: {
      topCoach: "Top coach",
      newCoach: "New coach",
      courseSingular: "course",
      coursePlural: "courses",
      viewProfile: "View profile",
      ariaViewProfile: (name: string) => `View ${name}'s profile`,
    },
    coachProfile: {
      notFoundTitle: "Coach not found",
      notFoundBody: "The coach you're looking for doesn't exist or has been removed.",
      backToCoaches: "Back to coaches",
      errorTitle: "Something went wrong",
      errorBody: "We couldn't load the coach profile. Please try again.",
      retry: "Retry",
      share: "Share",
      saveCoach: "Save coach",
      saved: "Saved",
      shareText: (name: string) => `Check out ${name} on Chaletcoaching`,
      about: "About",
      readMore: "Read more",
      readLess: "Read less",
      focusTitle: "Coaching focus",
      goals: "Goals",
      focusAreas: "Focus areas",
      level: "Level:",
      training: "Training:",
      languages: "Languages:",
      requestCourse: "Request a coach course",
      requestSubtitle: "Get a personalized training plan tailored to your goals",
      trust: ["Coach-led structure", "Clear token pricing", "Safety-first guidance"],
      bookingTitle: "Book a Training Session",
      bookingRate: (rate: string) => `${rate} tokens/hour · Select a date & time that works for you`,
      bookingButton: "Book a session",
      whatYouReceiveTitle: "What you receive",
      whatYouReceive: [
        "Weekly structure with clear progression",
        "Session plan with exercises and guidance",
        "Intensity and recovery recommendations",
        "Equipment-aware alternatives",
        "Simple checkpoints to track progress",
        "Warm-up and cooldown guidance",
      ],
      relatedTitle: "Related coaches",
      faqTitle: "FAQ",
      faqItems: [
        {
          id: "what-is-request",
          question: "What is a coach course request?",
          answer: "A coach course request lets you ask a coach to create a personalized training plan for you. The coach will design a structured program based on your goals, level, and preferences.",
        },
        {
          id: "how-tokens-work",
          question: "How do tokens work?",
          answer: "100 tokens = €1.00 / £0.87 / $1.19. You spend tokens when requesting coach courses or generating Instant AI courses. Tokens never expire.",
        },
        {
          id: "instant-ai-instead",
          question: "Can I use Instant AI instead?",
          answer: "Yes. Instant AI generates a course in minutes, while coach courses are personalized by your coach. Both options are available on the platform.",
        },
        {
          id: "where-see-requests",
          question: "Where can I see my requests?",
          answer: "You can track all your coach course requests in your dashboard. You'll see the status, updates, and can manage your requests there.",
        },
      ],
    },
    requestCoachForm: {
      successTitle: "Request received",
      successBody: "Next: you can track it in your dashboard.",
      dashboard: "Go to dashboard",
      title: "Tell your coach what you want",
      subtitle: "A few details help tailor your plan.",
      required: "Required",
      labels: {
        goal: "Goal",
        level: "Level",
        trainingType: "Training type",
        equipment: "Equipment",
        daysPerWeek: "Days per week",
        notes: "Notes (optional)",
      },
      placeholders: {
        notes: "Any specific preferences, injuries, or goals you'd like to mention...",
      },
      options: {
        goal: "Select goal...",
        level: "Select level...",
        trainingType: "Select training type...",
        equipment: "Select equipment...",
        daysPerWeek: "Select days...",
        days: (count: string) => `${count} days`,
      },
      costTitle: "Coach request cost",
      base: "Base",
      totalCost: "Total cost",
      loadingBalance: "Loading balance...",
      balance: "Balance:",
      notEnoughTokens: "Not enough tokens",
      insufficientTokens: "Insufficient tokens",
      haveNeed: (have: string, need: string) => `You have ${have}, need ${need}`,
      needButHave: (need: string, have: string) => `You need ${need} but only have ${have}`,
      topUp: "Top up tokens",
      chargedWhenSubmit: "Tokens are charged when you submit the request.",
      completeRequired: "Complete required fields to see total",
      sendRequest: "Send request",
      signInToSend: "Sign in to send your request",
      submitError: "Failed to submit request",
      notEnoughSubmitError: "Not enough tokens to submit request",
    },
    bookSessionModal: {
      title: "Book a Training Session",
      withCoach: (coachName: string, rate: string) => `with ${coachName} · ${rate} tokens/hour`,
      close: "Close modal",
      steps: { date: "Date", time: "Time", confirm: "Confirm" },
      duration: "Session Duration",
      cost: "Cost:",
      days: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
      months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
      noSlots: "No available slots for this date and duration.",
      pickAnotherDate: "Pick another date",
      durationHint: (hours: number) => `Selecting a start time books a ${hours}-hour block ending at ${hours} hours later.`,
      coach: "Coach",
      date: "Date",
      time: "Time",
      confirmDuration: "Duration",
      hour: "hour",
      hours: "hours",
      insufficient: (have: string, need: string) => `Insufficient balance. You have ${have} tokens but need ${need}.`,
      notes: "Notes (optional)",
      notesPlaceholder: "Anything the coach should know...",
      bookingFailed: "Booking failed. Please try again.",
      booking: "Booking...",
      confirmBooking: (cost: string) => `Confirm Booking — ${cost} tokens`,
    },
    becomeCoach: {
      title: "Become a Coach",
      subtitle: "Join our platform and help users achieve their fitness goals with structured, coach-led courses enhanced by AI support.",
      offerTitle: "What We Offer",
      offerItems: [
        "Platform to showcase your expertise and build your coaching brand",
        "AI tools to streamline course creation and delivery",
        "Token-based compensation model",
        "Support for various training specializations",
      ],
      requirementsTitle: "Requirements",
      requirementsItems: [
        "Certified fitness professional or equivalent experience",
        "Ability to create structured, progressive training programs",
        "Commitment to quality and safety standards",
      ],
      apply: "Contact Us to Apply",
      backHome: "Back to Home",
    },
  },
  tr: {
    coachesList: {
      title: "Koçunu bul",
      subtitle: "Koçları hedefe, stile ve antrenman türüne göre inceleyin.",
      searchPlaceholder: "Koç veya uzmanlık ara",
      filtersButton: "Filtreler",
      sort: [
        { value: "recommended", label: "Önerilen" },
        { value: "top-rated", label: "En yüksek puanlı" },
        { value: "newest", label: "En yeni" },
      ],
      quickFilters: [
        { label: "Güç", type: "goal", value: "Strength" },
        { label: "Yağ kaybı", type: "goal", value: "Fat loss" },
        { label: "Mobilite", type: "goal", value: "Mobility" },
        { label: "Dayanıklılık", type: "goal", value: "Endurance" },
        { label: "Duruş", type: "goal", value: "Posture" },
        { label: "Ev", type: "trainingType", value: "Home" },
        { label: "Spor salonu", type: "trainingType", value: "Gym" },
      ],
      errorTitle: "Bir şeyler ters gitti",
      errorFallback: "Koçlar yüklenemedi",
      retry: "Tekrar dene",
      noMatchesTitle: "Eşleşme yok",
      noMatchesBody: "Filtreleri temizlemeyi veya farklı bir arama yapmayı deneyin.",
      clearFilters: "Filtreleri temizle",
      emptyTitle: "Henüz koç yok",
      emptyBody: "Platformdaki ilk koç olmak ister misiniz?",
      becomeCoach: "Koç ol",
      ctaTitle: "Koç musunuz?",
      ctaBody: "Başvurun ve koçluğunuzu platformumuz üzerinden sunun.",
    },
    coachFilters: {
      title: "Filtreler",
      clear: "Temizle",
      apply: "Uygula",
      clearFilters: "Filtreleri temizle",
      sections: {
        goals: "Hedefler",
        level: "Seviye",
        trainingType: "Antrenman türü",
        languages: "Diller",
        focusAreas: "Odak alanları",
      },
    },
    coachCard: {
      topCoach: "En iyi koç",
      newCoach: "Yeni koç",
      courseSingular: "program",
      coursePlural: "program",
      viewProfile: "Profili gör",
      ariaViewProfile: (name: string) => `${name} profilini gör`,
    },
    coachProfile: {
      notFoundTitle: "Koç bulunamadı",
      notFoundBody: "Aradığınız koç mevcut değil veya kaldırılmış.",
      backToCoaches: "Koçlara dön",
      errorTitle: "Bir şeyler ters gitti",
      errorBody: "Koç profilini yükleyemedik. Lütfen tekrar deneyin.",
      retry: "Tekrar dene",
      share: "Paylaş",
      saveCoach: "Koçu kaydet",
      saved: "Kaydedildi",
      shareText: (name: string) => `${name} adlı koçu Chaletcoaching'de incele`,
      about: "Hakkında",
      readMore: "Devamını oku",
      readLess: "Daha az göster",
      focusTitle: "Koçluk odağı",
      goals: "Hedefler",
      focusAreas: "Odak alanları",
      level: "Seviye:",
      training: "Antrenman:",
      languages: "Diller:",
      requestCourse: "Koçtan program iste",
      requestSubtitle: "Hedeflerinize göre kişiselleştirilmiş bir antrenman planı alın",
      trust: ["Koç liderliğinde yapı", "Net token fiyatlandırması", "Güvenlik öncelikli yönlendirme"],
      bookingTitle: "Antrenman seansı rezerve et",
      bookingRate: (rate: string) => `${rate} token/saat · Size uygun tarih ve saati seçin`,
      bookingButton: "Seans rezerve et",
      whatYouReceiveTitle: "Neler alırsınız",
      whatYouReceive: [
        "Net ilerlemeli haftalık yapı",
        "Egzersiz ve yönlendirme içeren seans planı",
        "Yoğunluk ve toparlanma önerileri",
        "Ekipmana göre alternatifler",
        "İlerlemeyi takip etmek için basit kontrol noktaları",
        "Isınma ve soğuma yönlendirmesi",
      ],
      relatedTitle: "Benzer koçlar",
      faqTitle: "SSS",
      faqItems: [
        {
          id: "what-is-request",
          question: "Koç programı talebi nedir?",
          answer: "Koç programı talebi, bir koçtan sizin için kişiselleştirilmiş bir antrenman planı hazırlamasını istemenizi sağlar.",
        },
        {
          id: "how-tokens-work",
          question: "Tokenlar nasıl çalışır?",
          answer: "100 token = €1.00 / £0.87 / $1.19. Koç programı talep ederken veya Instant AI programları üretirken token harcarsınız. Tokenların süresi dolmaz.",
        },
        {
          id: "instant-ai-instead",
          question: "Bunun yerine Instant AI kullanabilir miyim?",
          answer: "Evet. Instant AI dakikalar içinde bir program üretir, koç programları ise koçunuz tarafından kişiselleştirilir. Platformda her iki seçenek de mevcuttur.",
        },
        {
          id: "where-see-requests",
          question: "Taleplerimi nerede görebilirim?",
          answer: "Tüm koç programı taleplerinizi panelinizde takip edebilirsiniz. Durumu ve güncellemeleri görür, taleplerinizi oradan yönetirsiniz.",
        },
      ],
    },
    requestCoachForm: {
      successTitle: "Talep alındı",
      successBody: "Sonraki adım: panelinizden takip edebilirsiniz.",
      dashboard: "Panele git",
      title: "Koçunuza ne istediğinizi anlatın",
      subtitle: "Birkaç detay planınızı daha iyi uyarlamaya yardımcı olur.",
      required: "Zorunlu",
      labels: {
        goal: "Hedef",
        level: "Seviye",
        trainingType: "Antrenman türü",
        equipment: "Ekipman",
        daysPerWeek: "Haftada gün",
        notes: "Notlar (opsiyonel)",
      },
      placeholders: {
        notes: "Belirtmek istediğiniz özel tercihler, sakatlıklar veya hedefler...",
      },
      options: {
        goal: "Hedef seçin...",
        level: "Seviye seçin...",
        trainingType: "Antrenman türü seçin...",
        equipment: "Ekipman seçin...",
        daysPerWeek: "Gün seçin...",
        days: (count: string) => `${count} gün`,
      },
      costTitle: "Koç talebi maliyeti",
      base: "Temel",
      totalCost: "Toplam maliyet",
      loadingBalance: "Bakiye yükleniyor...",
      balance: "Bakiye:",
      notEnoughTokens: "Yeterli token yok",
      insufficientTokens: "Yetersiz token",
      haveNeed: (have: string, need: string) => `${have} var, ${need} gerekiyor`,
      needButHave: (need: string, have: string) => `${need} gerekiyor ama sadece ${have} var`,
      topUp: "Token yükle",
      chargedWhenSubmit: "Tokenlar talebi gönderdiğinizde düşülür.",
      completeRequired: "Toplamı görmek için zorunlu alanları tamamlayın",
      sendRequest: "Talebi gönder",
      signInToSend: "Talebinizi göndermek için giriş yapın",
      submitError: "Talep gönderilemedi",
      notEnoughSubmitError: "Talebi göndermek için yeterli token yok",
    },
    bookSessionModal: {
      title: "Antrenman seansı rezerve et",
      withCoach: (coachName: string, rate: string) => `${coachName} ile · ${rate} token/saat`,
      close: "Pencereyi kapat",
      steps: { date: "Tarih", time: "Saat", confirm: "Onay" },
      duration: "Seans süresi",
      cost: "Maliyet:",
      days: ["Paz", "Pzt", "Sal", "Çar", "Per", "Cum", "Cmt"],
      months: ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
      noSlots: "Bu tarih ve süre için uygun saat yok.",
      pickAnotherDate: "Başka tarih seç",
      durationHint: (hours: number) => `Başlangıç saati seçildiğinde ${hours} saatlik blok rezerve edilir.`,
      coach: "Koç",
      date: "Tarih",
      time: "Saat",
      confirmDuration: "Süre",
      hour: "saat",
      hours: "saat",
      insufficient: (have: string, need: string) => `Yetersiz bakiye. ${have} tokenınız var, ${need} gerekiyor.`,
      notes: "Notlar (opsiyonel)",
      notesPlaceholder: "Koçun bilmesi gereken bir şey var mı?",
      bookingFailed: "Rezervasyon başarısız. Lütfen tekrar deneyin.",
      booking: "Rezerve ediliyor...",
      confirmBooking: (cost: string) => `Rezervasyonu onayla — ${cost} token`,
    },
    becomeCoach: {
      title: "Koç ol",
      subtitle: "Platformumuza katılın ve kullanıcıların AI desteğiyle güçlendirilmiş, koç liderliğinde yapılandırılmış programlarla fitness hedeflerine ulaşmasına yardımcı olun.",
      offerTitle: "Neler sunuyoruz",
      offerItems: [
        "Uzmanlığınızı sergilemek ve koçluk markanızı büyütmek için platform",
        "Program oluşturma ve teslim sürecini kolaylaştıran AI araçları",
        "Token bazlı ödeme modeli",
        "Farklı antrenman uzmanlıkları için destek",
      ],
      requirementsTitle: "Gereksinimler",
      requirementsItems: [
        "Sertifikalı fitness profesyoneli veya eşdeğer deneyim",
        "Yapılandırılmış, ilerlemeli antrenman programları oluşturabilme",
        "Kalite ve güvenlik standartlarına bağlılık",
      ],
      apply: "Başvuru için iletişime geç",
      backHome: "Ana sayfaya dön",
    },
  },
} as const;

export function getCoachesCopy(locale: Locale) {
  return COACHES_COPY[locale] ?? COACHES_COPY.en;
}

export function getCoachValueLabel(value: string, locale: Locale): string {
  const labels = valueLabels[locale] ?? valueLabels.en;
  return labels[value as keyof typeof labels] ?? value;
}

export function getCoachOptions(values: readonly string[], locale: Locale, placeholder?: string) {
  const options = values.map((value) => ({ value, label: getCoachValueLabel(value, locale) }));
  return placeholder ? [{ value: "", label: placeholder }, ...options] : options;
}

export function localizeCoachDisplay<T extends CoachLike>(coach: T, locale: Locale): T {
  const coachWithRaw = {
    ...coach,
    rawGoals: coach.goals,
    rawLevel: coach.level,
    rawTrainingType: coach.trainingType,
    rawFocusAreas: coach.focusAreas,
    rawSpecialties: coach.specialties,
  };

  if (locale === "en") return coachWithRaw;

  return {
    ...coachWithRaw,
    bio: coachBioTr[coach.slug] ?? coach.bio,
    specialties: coach.specialties.map((item) => getCoachValueLabel(item, locale)),
    goals: coach.goals.map((item) => getCoachValueLabel(item, locale)),
    level: getCoachValueLabel(coach.level, locale),
    trainingType: getCoachValueLabel(coach.trainingType, locale),
    focusAreas: coach.focusAreas.map((item) => getCoachValueLabel(item, locale)),
  };
}

export function getRequestLocale(request: Request): Locale {
  const url = new URL(request.url);
  const queryLocale = url.searchParams.get("locale");
  if (isLocale(queryLocale)) return queryLocale;

  const cookieHeader = request.headers.get("cookie") ?? "";
  const cookieLocale = cookieHeader
    .split(";")
    .map((part) => part.trim())
    .find((part) => part.startsWith(`${LOCALE_COOKIE_NAME}=`))
    ?.split("=")[1];

  return isLocale(cookieLocale) ? cookieLocale : DEFAULT_LOCALE;
}
