import type { Locale } from "@/lib/i18n/config";

export type LegalPageId = "terms" | "privacy" | "cookies" | "refunds";

type LegalSection = {
  title: string;
  paragraphs?: string[];
  bullets?: string[];
};

type LegalPageCopy = {
  title: string;
  accent: string;
  badge: string;
  dateLabel: string;
  effectiveDate: string;
  metadataTitle: string;
  metadataDescription: string;
  disclaimer?: string;
  sections: LegalSection[];
};

const company = "CHALET AQUARIUS LTD";
const address = "20 Wenlock Road, London, England, N1 7GU";
const email = "info@chaletcoaching.co.uk";
const phone = "+44 7782 358363";

export const LEGAL_COPY: Record<Locale, Record<LegalPageId, LegalPageCopy>> = {
  en: {
    terms: {
      title: "Terms and",
      accent: "Conditions",
      badge: "Policy",
      dateLabel: "Last Updated:",
      effectiveDate: "January 17, 2026",
      metadataTitle: "Terms and Conditions - Chaletcoaching",
      metadataDescription: "Terms and conditions for using Chaletcoaching services.",
      sections: [
        {
          title: "1. Introduction and Acceptance",
          paragraphs: [
            `These Terms and Conditions form a legally binding agreement between ${company}, company number 15587263, registered at ${address}, and the user accessing chaletcoaching.co.uk or purchasing our fitness content and services.`,
            "By registering an account, purchasing Tokens, requesting a course, or downloading digital content, you agree to these Terms. If you do not agree, you must stop using the Service.",
            "Chaletcoaching provides digital fitness educational content, including AI-generated courses and plans prepared by human trainers. Content is delivered digitally, usually through dashboard access or PDF files.",
          ],
        },
        {
          title: "2. Definitions",
          bullets: [
            "Account: the registered user profile on the Chaletcoaching platform.",
            "Tokens: internal virtual credits used only within the Service to buy Courses.",
            "Course or Plan: a digital fitness guide, PDF, or program generated by AI or prepared by a trainer.",
            "Dashboard: the private area where users manage Tokens and downloaded content.",
            "Trainer: a human fitness professional engaged to create workout plans.",
          ],
        },
        {
          title: "3. Account Eligibility and Security",
          paragraphs: [
            "You must be at least 18 years old and legally able to enter into a binding agreement.",
            "You agree to provide accurate account, physical, goal, and limitation information. Incorrect inputs may produce unsuitable plans.",
            "You are responsible for protecting your login credentials and for activity under your Account.",
          ],
        },
        {
          title: "4. Token System and Virtual Currency",
          paragraphs: [
            "Services are purchased using Tokens. Tokens may be sold in packages such as Starter Spark, Momentum Pack, Elite Performance, or custom amounts.",
            "Tokens are not cryptocurrency, financial instruments, or real money. They are non-transferable and cannot be redeemed for cash except where required by law.",
            "Tokens do not expire while the Account remains active, but may be cancelled if the Account is terminated for breach of these Terms.",
          ],
        },
        {
          title: "5. Service Delivery and Digital Content",
          paragraphs: [
            "Courses are delivered as downloadable digital files or dashboard-accessible digital content.",
            "AI Courses are usually generated within minutes. Trainer-created Courses require manual work and delivery may vary based on complexity and trainer availability.",
            "We are not liable for delays caused by technical issues, email delivery problems, spam filtering, or trainer availability.",
          ],
        },
        {
          title: "6. Health Disclaimer",
          paragraphs: [
            "The Service provides educational fitness information only. It is not medical advice, diagnosis, or treatment.",
            "Consult a physician or healthcare professional before starting any fitness program.",
            "Exercise involves risk. You use all plans at your own risk and agree that the Company is not liable for injury, health impairment, or death arising from use of the Service.",
          ],
        },
        {
          title: "7. Intellectual Property and Usage Rights",
          paragraphs: [
            "After purchase, you receive a limited, non-exclusive, non-transferable personal license to use the Course for personal, non-commercial purposes.",
            "You must not resell, redistribute, publish, share, or remove proprietary notices from the content.",
          ],
        },
        {
          title: "8. Pricing and Payment",
          paragraphs: [
            "We accept Visa and MasterCard and process transactions in GBP, EUR, and USD.",
            "Prices and Token costs may change. Changes do not affect Tokens already purchased or Courses already ordered.",
          ],
        },
        {
          title: "9. Cancellation and Refunds",
          paragraphs: [
            "Digital content starts immediately once generated, downloaded, or delivered. Cooling-off rights may be lost when digital performance begins.",
            "Unused Token package refunds may be requested within 14 days where no Tokens from that package were used. Used or partially used packages are generally non-refundable.",
            "If a file is technically defective, contact support for a replacement or a possible Token refund for that specific item.",
          ],
        },
        {
          title: "10. Liability, Governing Law, and Contact",
          paragraphs: [
            "To the fullest extent permitted by law, liability is limited to the amount paid by you for the Service in the 12 months before the claim.",
            "These Terms are governed by the laws of England and Wales and disputes are subject to the courts of London, England.",
            `Contact: ${company}, ${address}, ${email}, ${phone}.`,
          ],
        },
      ],
    },
    privacy: {
      title: "Privacy",
      accent: "Policy",
      badge: "Policy",
      dateLabel: "Effective date:",
      effectiveDate: "January 17, 2026",
      metadataTitle: "Privacy Policy - Chaletcoaching",
      metadataDescription: "Privacy policy and data handling practices for Chaletcoaching.",
      sections: [
        {
          title: "1. Introduction",
          paragraphs: [
            `${company} is committed to protecting your privacy and personal data when you use chaletcoaching.co.uk and the Chaletcoaching fitness platform.`,
            `We act as Data Controller for personal data you provide directly. Company number: 15587263. Registered address: ${address}. Email: ${email}.`,
            "The Service is intended for users aged 18 and over.",
          ],
        },
        {
          title: "2. Data We Collect",
          bullets: [
            "Account information: name, email address, phone number, and password.",
            "Physical and health-related data: age, gender, height, weight, goals, fitness level, lifestyle, limitations, and injuries.",
            "Transaction data: Token purchases, payment history, balances, and order references.",
            "Technical and usage data: IP address, browser, device, time zone, dashboard activity, downloads, cookies, and local storage.",
            "Support communications and trainer-request information.",
          ],
        },
        {
          title: "3. How We Use Data and Legal Basis",
          paragraphs: [
            "We use data to create fitness plans, process Token payments, deliver digital content, manage Accounts, provide support, improve the Service, and meet legal obligations.",
            "Health-related inputs are processed with explicit consent and only for plan generation and safety personalization.",
            "Payment and accounting records may be retained to comply with legal, tax, fraud-prevention, and dispute obligations.",
          ],
        },
        {
          title: "4. Sharing, Security, and Retention",
          paragraphs: [
            "We may share data with service providers such as hosting, payment, analytics, support, email, accounting, and legal providers where needed to operate the Service.",
            "We use reasonable technical and organizational safeguards, but no online service can guarantee absolute security.",
            "We keep data only as long as needed for the purposes described, legal obligations, dispute handling, and legitimate business records.",
          ],
        },
        {
          title: "5. Your Rights",
          bullets: [
            "Access, correction, deletion, restriction, objection, and data portability where applicable.",
            "Withdrawal of consent for consent-based processing.",
            "Complaint to the UK Information Commissioner's Office or another competent authority.",
          ],
        },
        {
          title: "6. Cookies, Third Parties, and Contact",
          paragraphs: [
            "We use cookies and similar technologies for login, preferences, analytics, performance, and security.",
            "Our website may link to third-party websites. We are not responsible for their privacy practices.",
            `For privacy questions, contact ${email}.`,
          ],
        },
      ],
    },
    cookies: {
      title: "Cookies",
      accent: "Policy",
      badge: "Policy",
      dateLabel: "Effective date:",
      effectiveDate: "January 17, 2026",
      metadataTitle: "Cookies Policy - Chaletcoaching",
      metadataDescription: "Cookies policy and tracking technologies information for Chaletcoaching.",
      sections: [
        {
          title: "1. Introduction",
          paragraphs: [
            `This Cookies Policy explains how ${company} uses cookies and similar technologies on chaletcoaching.co.uk and the fitness coaching dashboard.`,
            "It should be read together with our Privacy Policy.",
          ],
        },
        {
          title: "2. What Cookies Are",
          paragraphs: [
            "Cookies are small text files placed on your device when you visit a website. They help websites work efficiently, secure accounts, remember preferences, and provide usage information.",
            "We may also use local storage, pixels, tags, and similar browser technologies.",
          ],
        },
        {
          title: "3. How We Use Cookies",
          bullets: [
            "Strictly necessary cookies for login, dashboard access, secure sessions, and payment flow.",
            "Functional cookies for preferences such as selected language, currency, and region.",
            "Analytics and performance cookies to understand traffic and improve the Service.",
            "Marketing or targeting cookies only where enabled and permitted.",
          ],
        },
        {
          title: "4. Examples and Third Parties",
          paragraphs: [
            "Examples may include session cookies, authentication cookies, language/currency preference cookies, cookie consent storage, analytics cookies, and payment security cookies.",
            "Third parties such as payment processors, analytics providers, and social platforms may set their own cookies where their services are used.",
          ],
        },
        {
          title: "5. Managing Cookies",
          paragraphs: [
            "You can manage cookies through browser settings and through any consent controls we provide.",
            "Blocking essential cookies may prevent access to the dashboard, Token purchases, PDF downloads, or secure account features.",
            "To learn more about cookies, visit www.allaboutcookies.org.",
          ],
        },
        {
          title: "6. Updates and Contact",
          paragraphs: [
            "We may update this Cookies Policy from time to time. Changes will be posted on this page with an updated effective date.",
            `Questions: ${email}.`,
          ],
        },
      ],
    },
    refunds: {
      title: "Refund and Return",
      accent: "Policy",
      badge: "Policy",
      dateLabel: "Effective Date:",
      effectiveDate: "January 16, 2026",
      metadataTitle: "Refund & Returns Policy - Chaletcoaching",
      metadataDescription: "Refund policy and token system information for Chaletcoaching.",
      sections: [
        {
          title: "1. Introduction",
          paragraphs: [
            `This Refund and Return Policy governs order cancellation, refund requests for Token packages, and disputes about digital content provided by ${company}.`,
            "By purchasing Tokens or exchanging them for Fitness Courses, you agree to this Policy alongside our Terms and Conditions.",
          ],
        },
        {
          title: "2. Refund of Token Packages",
          paragraphs: [
            "Unused Token packages may be eligible for monetary refund within 14 days of the transaction date if none of the Tokens from that package have been used.",
            "Once any part of a Token package is used, the package is considered activated and no partial refund is issued for the remaining Tokens.",
            "Eligible refunds may be reduced by processing fees, typically 3-5%, to cover merchant and administrative costs.",
          ],
        },
        {
          title: "3. Course Order Cancellation",
          paragraphs: [
            "AI-generated Courses are delivered instantly or within minutes and are non-refundable once generation begins.",
            "Trainer-created Courses may be cancelled only before the trainer starts work. Once in progress or delivered, cancellation and Token refund are not available.",
          ],
        },
        {
          title: "4. Digital Content and Results",
          paragraphs: [
            "Digital content is exempt from standard withdrawal rights once download, delivery, or generation begins.",
            "Fitness results are not guaranteed. Dissatisfaction with difficulty, style, or results is not a valid refund reason.",
          ],
        },
        {
          title: "5. Technical Issues",
          paragraphs: [
            "If a PDF is corrupted, blank, or inaccessible, contact support within 48 hours of purchase.",
            "We will try to provide a replacement. If we cannot provide a working file, Tokens used for that specific order may be refunded.",
            "If you paid Tokens but did not receive the Course, check spam/junk folders and contact support immediately.",
          ],
        },
        {
          title: "6. Monetary Refunds, Disputes, and Contact",
          paragraphs: [
            "Approved monetary refunds are processed to the original Visa or MasterCard payment method. Bank processing may take 5-10 business days.",
            "Chargebacks without first contacting support may lead to Account suspension while the dispute is investigated.",
            `For refund requests, include your User ID and order reference and contact ${email}.`,
          ],
        },
      ],
    },
  },
  tr: {
    terms: {
      title: "Şartlar ve",
      accent: "Koşullar",
      badge: "Politika",
      dateLabel: "Son güncelleme:",
      effectiveDate: "17 Ocak 2026",
      metadataTitle: "Şartlar ve Koşullar - Chaletcoaching",
      metadataDescription: "Chaletcoaching hizmetlerini kullanma şartları ve koşulları.",
      disclaimer: "Bu Türkçe metin kolaylık amacıyla sunulan bir çeviridir. Herhangi bir çelişki durumunda İngilizce sürüm geçerlidir.",
      sections: [
        { title: "1. Giriş ve Kabul", paragraphs: [`Bu Şartlar, ${company} ile chaletcoaching.co.uk sitesine erişen veya fitness içerikleri satın alan kullanıcı arasında bağlayıcı bir anlaşmadır.`, "Hesap oluşturarak, Token satın alarak, kurs talep ederek veya dijital içerik indirerek bu Şartları kabul etmiş olursunuz.", "Chaletcoaching; AI tarafından oluşturulan veya insan antrenörler tarafından hazırlanan dijital fitness eğitim içerikleri sağlar."] },
        { title: "2. Tanımlar", bullets: ["Hesap: Chaletcoaching platformundaki kayıtlı kullanıcı profili.", "Token: yalnızca Hizmet içinde kurs satın almak için kullanılan dahili sanal kredi.", "Kurs veya Plan: AI veya antrenör tarafından oluşturulan dijital fitness rehberi.", "Panel: Tokenları ve indirilen içerikleri yönetilen özel alan.", "Antrenör: kişisel plan hazırlayan fitness profesyoneli."] },
        { title: "3. Hesap Uygunluğu ve Güvenlik", paragraphs: ["Hizmeti kullanmak için en az 18 yaşında olmanız gerekir.", "Fiziksel ölçü, hedef ve sınırlama bilgilerinin doğru verilmesinden siz sorumlusunuz.", "Giriş bilgilerinizin gizliliğini korumak ve hesabınızdaki aktivitelerden sorumlu olmak size aittir."] },
        { title: "4. Token Sistemi", paragraphs: ["Hizmetler Token ile satın alınır. Token paketleri veya özel miktarlar sunulabilir.", "Tokenlar kripto para, finansal araç veya gerçek para değildir; devredilemez ve yasaların gerektirdiği durumlar dışında nakde çevrilemez.", "Hesap aktif kaldığı sürece Tokenlar sona ermez; ancak Şart ihlali halinde iptal edilebilir."] },
        { title: "5. Hizmet Teslimi", paragraphs: ["Kurslar indirilebilir dijital dosya veya panel üzerinden erişilen içerik olarak teslim edilir.", "AI Kursları genellikle dakikalar içinde hazırlanır. Antrenör kurslarının teslimi karmaşıklığa ve müsaitliğe bağlıdır.", "Teknik sorunlar, e-posta teslim problemleri veya antrenör yoğunluğundan kaynaklanan gecikmelerden sorumlu değiliz."] },
        { title: "6. Sağlık Uyarısı", paragraphs: ["Hizmet yalnızca eğitim amaçlı fitness bilgisi sağlar; tıbbi tavsiye, teşhis veya tedavi değildir.", "Herhangi bir fitness programına başlamadan önce doktorunuza danışmalısınız.", "Egzersiz risk içerir. Planları kendi sorumluluğunuzda kullanırsınız."] },
        { title: "7. Fikri Mülkiyet", paragraphs: ["Satın alma sonrası kişisel ve ticari olmayan kullanım için sınırlı, devredilemez bir lisans alırsınız.", "İçeriği satamaz, yeniden dağıtamaz, yayımlayamaz, paylaşamaz veya mülkiyet bildirimlerini kaldıramazsınız."] },
        { title: "8. Fiyatlandırma ve Ödeme", paragraphs: ["Visa ve MasterCard kabul edilir; işlemler GBP, EUR ve USD ile yapılabilir.", "Fiyatlar ve Token maliyetleri değişebilir; değişiklikler önceden satın alınmış Tokenları veya sipariş edilmiş kursları etkilemez."] },
        { title: "9. İptal ve İadeler", paragraphs: ["Dijital performans başladığında cayma hakları kaybedilebilir.", "Kullanılmamış Token paketleri, paketten hiç Token kullanılmadıysa 14 gün içinde iade için değerlendirilebilir.", "Teknik olarak kusurlu dosyalarda destek ekibiyle iletişime geçin; değiştirme veya ilgili Token iadesi değerlendirilebilir."] },
        { title: "10. Sorumluluk, Hukuk ve İletişim", paragraphs: ["Yasal olarak izin verilen en geniş ölçüde sorumluluk, talep öncesindeki 12 ayda Hizmet için ödediğiniz tutarla sınırlıdır.", "Bu Şartlar İngiltere ve Galler yasalarına tabidir; uyuşmazlıklarda Londra mahkemeleri yetkilidir.", `İletişim: ${company}, ${address}, ${email}, ${phone}.`] },
      ],
    },
    privacy: {
      title: "Gizlilik",
      accent: "Politikası",
      badge: "Politika",
      dateLabel: "Yürürlük tarihi:",
      effectiveDate: "17 Ocak 2026",
      metadataTitle: "Gizlilik Politikası - Chaletcoaching",
      metadataDescription: "Chaletcoaching gizlilik politikası ve veri işleme uygulamaları.",
      disclaimer: "Bu Türkçe metin kolaylık amacıyla sunulan bir çeviridir. Herhangi bir çelişki durumunda İngilizce sürüm geçerlidir.",
      sections: [
        { title: "1. Giriş", paragraphs: [`${company}, chaletcoaching.co.uk ve fitness platformunu kullanırken kişisel verilerinizi korumayı taahhüt eder.`, `Doğrudan sağladığınız veriler için Veri Sorumlusu olarak hareket ederiz. Şirket numarası: 15587263. Adres: ${address}. E-posta: ${email}.`, "Hizmet 18 yaş ve üzeri kullanıcılar içindir."] },
        { title: "2. Topladığımız Veriler", bullets: ["Hesap bilgileri: ad, e-posta, telefon ve şifre.", "Fiziksel ve sağlıkla ilgili veriler: yaş, cinsiyet, boy, kilo, hedefler, seviye, yaşam tarzı, kısıtlamalar ve sakatlıklar.", "İşlem verileri: Token satın alımları, ödeme geçmişi, bakiye ve sipariş referansları.", "Teknik ve kullanım verileri: IP adresi, tarayıcı, cihaz, panel kullanımı, indirmeler, çerezler ve local storage.", "Destek yazışmaları ve antrenör talep bilgileri."] },
        { title: "3. Verileri Kullanma Amacı", paragraphs: ["Verileri fitness planı oluşturmak, Token ödemelerini işlemek, dijital içerik teslim etmek, hesapları yönetmek, destek sağlamak ve yasal yükümlülükleri yerine getirmek için kullanırız.", "Sağlıkla ilgili girdiler açık rıza ile ve yalnızca plan kişiselleştirme ve güvenlik amacıyla işlenir."] },
        { title: "4. Paylaşım, Güvenlik ve Saklama", paragraphs: ["Veriler hizmet sağlayıcılarla yalnızca Hizmeti işletmek için gerekli olduğunda paylaşılabilir.", "Makul teknik ve organizasyonel güvenlik önlemleri kullanırız, ancak hiçbir çevrimiçi hizmet mutlak güvenlik garanti edemez.", "Verileri amaç, yasal yükümlülük ve uyuşmazlık gerektirdiği sürece saklarız."] },
        { title: "5. Haklarınız", bullets: ["Erişim, düzeltme, silme, kısıtlama, itiraz ve veri taşınabilirliği.", "Rızaya dayalı işleme için rızayı geri çekme.", "Yetkili veri koruma otoritesine şikayet etme."] },
        { title: "6. Çerezler ve İletişim", paragraphs: ["Giriş, tercihler, analiz, performans ve güvenlik için çerezler ve benzer teknolojiler kullanırız.", "Üçüncü taraf sitelere bağlantılar olabilir; onların gizlilik uygulamalarından sorumlu değiliz.", `Sorular için: ${email}.`] },
      ],
    },
    cookies: {
      title: "Çerez",
      accent: "Politikası",
      badge: "Politika",
      dateLabel: "Yürürlük tarihi:",
      effectiveDate: "17 Ocak 2026",
      metadataTitle: "Çerez Politikası - Chaletcoaching",
      metadataDescription: "Chaletcoaching çerez ve izleme teknolojileri politikası.",
      disclaimer: "Bu Türkçe metin kolaylık amacıyla sunulan bir çeviridir. Herhangi bir çelişki durumunda İngilizce sürüm geçerlidir.",
      sections: [
        { title: "1. Giriş", paragraphs: [`Bu Çerez Politikası, ${company} tarafından chaletcoaching.co.uk ve fitness panelinde çerezlerin nasıl kullanıldığını açıklar.`, "Gizlilik Politikası ile birlikte okunmalıdır."] },
        { title: "2. Çerez Nedir?", paragraphs: ["Çerezler, bir web sitesini ziyaret ettiğinizde cihazınıza yerleştirilen küçük metin dosyalarıdır.", "Local storage, piksel, tag ve benzer tarayıcı teknolojileri de kullanılabilir."] },
        { title: "3. Çerezleri Nasıl Kullanıyoruz", bullets: ["Giriş, güvenli oturum ve ödeme akışı için zorunlu çerezler.", "Dil, para birimi ve bölge gibi tercihleri hatırlamak için işlevsel çerezler.", "Trafiği anlamak ve Hizmeti iyileştirmek için analiz ve performans çerezleri.", "Yalnızca izin verildiğinde pazarlama veya hedefleme çerezleri."] },
        { title: "4. Örnekler ve Üçüncü Taraflar", paragraphs: ["Oturum, kimlik doğrulama, dil/para birimi tercihi, çerez onayı, analiz ve ödeme güvenliği çerezleri kullanılabilir.", "Ödeme sağlayıcıları, analiz hizmetleri ve sosyal platformlar kendi çerezlerini ayarlayabilir."] },
        { title: "5. Çerezleri Yönetme", paragraphs: ["Çerezleri tarayıcı ayarlarınızdan ve sunduğumuz onay kontrollerinden yönetebilirsiniz.", "Zorunlu çerezleri engellemek panel, Token satın alma, PDF indirme veya güvenli hesap özelliklerini bozabilir.", "Daha fazla bilgi için www.allaboutcookies.org adresini ziyaret edebilirsiniz."] },
        { title: "6. Güncellemeler ve İletişim", paragraphs: ["Bu politika zaman zaman güncellenebilir ve yeni yürürlük tarihiyle yayımlanır.", `Sorular: ${email}.`] },
      ],
    },
    refunds: {
      title: "İade ve Geri Dönüş",
      accent: "Politikası",
      badge: "Politika",
      dateLabel: "Yürürlük tarihi:",
      effectiveDate: "16 Ocak 2026",
      metadataTitle: "İade Politikası - Chaletcoaching",
      metadataDescription: "Chaletcoaching iade politikası ve Token sistemi bilgileri.",
      disclaimer: "Bu Türkçe metin kolaylık amacıyla sunulan bir çeviridir. Herhangi bir çelişki durumunda İngilizce sürüm geçerlidir.",
      sections: [
        { title: "1. Giriş", paragraphs: [`Bu İade Politikası, ${company} tarafından sağlanan dijital içerikler için sipariş iptali, Token paketi iadeleri ve uyuşmazlıkları düzenler.`, "Token satın alarak veya Fitness Kursları için kullanarak bu Politikayı ve Şartlar ve Koşulları kabul edersiniz."] },
        { title: "2. Token Paketi İadesi", paragraphs: ["Hiç kullanılmamış Token paketleri, işlem tarihinden itibaren 14 gün içinde iade için değerlendirilebilir.", "Paketten herhangi bir Token kullanıldığında paket aktif kabul edilir ve kalan Tokenlar için kısmi iade yapılmaz.", "Uygun iadelerde ödeme sağlayıcı ve idari maliyetler için genellikle %3-5 işlem ücreti düşülebilir."] },
        { title: "3. Kurs Siparişi İptali", paragraphs: ["AI tarafından oluşturulan Kurslar anında veya dakikalar içinde teslim edilir ve üretim başladığında iade edilmez.", "Antrenör tarafından hazırlanan Kurslar yalnızca antrenör çalışmaya başlamadan önce iptal edilebilir."] },
        { title: "4. Dijital İçerik ve Sonuçlar", paragraphs: ["İndirme, teslim veya üretim başladıktan sonra dijital içerikte standart cayma hakları uygulanmayabilir.", "Fitness sonuçları garanti edilmez; zorluk, tarz veya sonuç memnuniyetsizliği iade nedeni değildir."] },
        { title: "5. Teknik Sorunlar", paragraphs: ["PDF bozuk, boş veya erişilemezse satın almadan sonraki 48 saat içinde destekle iletişime geçin.", "Çalışan bir dosya sağlanamazsa ilgili sipariş için kullanılan Tokenlar iade edilebilir.", "Token harcadığınız halde Kurs gelmediyse spam klasörünü kontrol edin ve destekle iletişime geçin."] },
        { title: "6. Para İadeleri, Uyuşmazlıklar ve İletişim", paragraphs: ["Onaylanan para iadeleri orijinal Visa veya MasterCard ödeme yöntemine yapılır. Banka işlemleri 5-10 iş günü sürebilir.", "Önce destekle iletişim kurulmadan yapılan chargeback talepleri hesap askıya alma sürecine yol açabilir.", `İade talebi için User ID ve sipariş referansını ekleyerek ${email} adresine yazın.`] },
      ],
    },
  },
};

export function getLegalCopy(locale: Locale, page: LegalPageId) {
  return (LEGAL_COPY[locale] ?? LEGAL_COPY.en)[page];
}
