import { THEME } from "@/lib/theme";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions — Chaletcoaching",
  description: "Terms and conditions for using Chaletcoaching services",
};

function Card({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="rounded-2xl border p-6"
      style={{ background: THEME.card, borderColor: THEME.cardBorder }}
    >
      {children}
    </div>
  );
}

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-5xl px-4 py-10 space-y-8" style={{ color: THEME.text }}>
      <header className="space-y-2">
        <div className="inline-flex items-center gap-2 text-xs font-medium rounded-full px-3 py-1"
             style={{ background: "#19191f", border: `1px solid ${THEME.cardBorder}`, color: THEME.secondary }}>
          Policy
        </div>
        <h1 className="text-3xl md:text-4xl font-extrabold leading-tight">
          Terms and <span style={{ color: THEME.accent }}>Conditions</span>
        </h1>
        <p className="opacity-80 text-sm">Last Updated: January 17, 2026</p>
      </header>

      {/* Introduction and Acceptance */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">1. Introduction and Acceptance</h2>
        <div className="space-y-3 opacity-90 text-sm">
          <p><strong>1.1. Parties.</strong> These Terms and Conditions (&quot;Terms&quot;) constitute a legally binding agreement between CHALET AQUARIUS LTD (&quot;Company&quot;, &quot;we&quot;, &quot;us&quot;, &quot;our&quot;), a company registered in England and Wales (Company Number: 15587263), with its registered office at 20 Wenlock Road, London, England, N1 7GU, and you (&quot;User&quot;, &quot;Customer&quot;, &quot;you&quot;), the individual accessing our website chaletcoaching.co.uk (the &quot;Site&quot;) or purchasing our fitness content and services (the &quot;Service&quot;).</p>
          <p><strong>1.2. Agreement.</strong> By registering an account, purchasing Tokens, or downloading any fitness course (PDF), you expressly agree to be bound by these Terms. If you do not agree, you must cease using the Service immediately.</p>
          <p><strong>1.3. Nature of Service.</strong> You acknowledge that CHALET AQUARIUS LTD provides digital fitness educational content. We offer fitness courses generated by Artificial Intelligence (&quot;AI Courses&quot;) and courses compiled by human trainers (&quot;Trainer Courses&quot;). All content is provided in digital format (PDF) and is accessed via the Site dashboard or email.</p>
        </div>
      </Card>

      {/* Definitions */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">2. Definitions</h2>
        <div className="space-y-2 opacity-90 text-sm">
          <p><strong>• Account:</strong> The registered user profile on the chaletcoaching.co.uk platform.</p>
          <p><strong>• Tokens:</strong> The internal virtual currency/credits used solely within the Site to purchase Courses. Tokens have no monetary value outside of our Service.</p>
          <p><strong>• Course / Plan:</strong> The digital fitness guide (PDF) purchased by the User, which may be AI-generated or Trainer-created.</p>
          <p><strong>• Dashboard:</strong> The private area of the Site where Users can manage their Tokens and download purchased content.</p>
          <p><strong>• Trainer:</strong> A human fitness professional engaged by the Company to create specific workout plans.</p>
          <p><strong>• AI:</strong> Artificial Intelligence algorithms used to generate instant fitness plans based on User inputs.</p>
        </div>
      </Card>

      {/* Account Eligibility and Security */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">3. Account Eligibility and Security</h2>
        <div className="space-y-3 opacity-90 text-sm">
          <p><strong>3.1. Eligibility.</strong> You must be at least 18 years old to use the Service. By creating an account, you represent and warrant that you meet this age requirement and have the legal capacity to enter into a binding contract.</p>
          <p><strong>3.2. Accuracy.</strong> You agree to provide current, complete, and accurate information regarding your physical metrics and goals when requesting a Course. Inaccurate data may lead to ineffective or unsuitable workout plans.</p>
          <p><strong>3.3. Security.</strong> You are responsible for maintaining the confidentiality of your login credentials. CHALET AQUARIUS LTD is not liable for any loss (including loss of Tokens) arising from unauthorized access to your Account.</p>
        </div>
      </Card>

      {/* Token System & Virtual Currency */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">4. Token System & Virtual Currency</h2>
        <div className="space-y-3 opacity-90 text-sm">
          <p><strong>4.1. Purchasing Tokens.</strong> Services on the Site are purchased using Tokens. Tokens are sold in packages (e.g., Starter Spark, Momentum Pack, Elite Performance) or custom amounts.</p>
          <ul className="list-disc pl-5 space-y-1 ml-4">
            <li>Starter Spark: 10,000 Tokens</li>
            <li>Momentum Pack: 20,000 Tokens</li>
            <li>Elite Performance: 30,000 Tokens</li>
          </ul>
          <p><strong>4.2. No Cash Value.</strong> Tokens are a limited license to use digital features of our Site. They are not cryptocurrency, financial instruments, or real money. Tokens are non-transferable and cannot be redeemed for cash, returned for a refund (except where required by law), or exchanged outside of the Service.</p>
          <p><strong>4.3. Expiration.</strong> Unless otherwise stated, Tokens do not expire as long as your Account remains active. However, we reserve the right to cancel Tokens if an Account is terminated for violation of these Terms.</p>
        </div>
      </Card>

      {/* Service Delivery & Digital Content */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">5. Service Delivery & Digital Content</h2>
        <div className="space-y-3 opacity-90 text-sm">
          <p><strong>5.1. Format.</strong> All Courses are delivered as downloadable digital files (PDF format).</p>
          <p><strong>5.2. Delivery Methods.</strong> Purchased Courses are:</p>
          <ul className="list-disc pl-5 space-y-1 ml-4">
            <li>Available for download in your Account Dashboard.</li>
            <li>Sent to the email address associated with your Account.</li>
          </ul>
          <p><strong>5.3. Delivery Timeframes.</strong></p>
          <ul className="list-disc pl-5 space-y-1 ml-4">
            <li><strong>AI Courses:</strong> Typically generated and delivered within minutes of purchase.</li>
            <li><strong>Trainer Courses:</strong> These require manual compilation. Delivery times vary based on complexity and Trainer availability, typically ranging from a few hours to several days.</li>
          </ul>
          <p><strong>5.4. Delays.</strong> While we strive to meet these timeframes, CHALET AQUARIUS LTD is not liable for technical delays, email delivery failures (e.g., spam filters), or Trainer delays due to high demand.</p>
        </div>
      </Card>

      {/* Health Disclaimer and Physical Activity */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">6. Health Disclaimer and Physical Activity</h2>
        <div className="space-y-3 opacity-90 text-sm">
          <p><strong>6.1. Not Medical Advice.</strong> The content provided by CHALET AQUARIUS LTD, whether AI-generated or Trainer-created, is for educational and informational purposes only. It is not medical advice, diagnosis, or treatment.</p>
          <p><strong>6.2. Consult a Physician.</strong> You should consult with a physician or other healthcare professional before starting this or any other fitness program to determine if it is right for your needs.</p>
          <p><strong>6.3. Assumption of Risk.</strong> Participation in any exercise program involves a risk of physical injury. By using our Services, you agree that you do so entirely at your own risk. CHALET AQUARIUS LTD, its officers, employees, and agents shall not be liable for any injury, health impairment, or death arising out of or in connection with the use of our fitness plans.</p>
        </div>
      </Card>

      {/* Intellectual Property & Usage Rights */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">7. Intellectual Property & Usage Rights</h2>
        <div className="space-y-3 opacity-90 text-sm">
          <p><strong>7.1. License.</strong> Upon purchase of a Course, we grant you a limited, non-exclusive, non-transferable, personal license to download and view the PDF for your personal, non-commercial use.</p>
          <p><strong>7.2. Prohibited Use.</strong> You strictly agree not to:</p>
          <ul className="list-disc pl-5 space-y-1 ml-4">
            <li>Resell, redistribute, or share the PDF files with third parties.</li>
            <li>Publish the content on other websites or social media.</li>
            <li>Remove any copyright or proprietary notices from the files.</li>
          </ul>
          <p><strong>7.3. Ownership.</strong> All content, site design, logos, and software are the intellectual property of CHALET AQUARIUS LTD.</p>
        </div>
      </Card>

      {/* Pricing and Payment */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">8. Pricing and Payment</h2>
        <div className="space-y-3 opacity-90 text-sm">
          <p><strong>8.1. Accepted Methods.</strong> We accept payments via Visa and MasterCard.</p>
          <p><strong>8.2. Currencies.</strong> We process transactions in GBP (£), EUR (€), and USD ($).</p>
          <div className="ml-4 space-y-1">
            <p><strong>Prices:</strong></p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Starter Spark: €100.00 / £75.69 / $182.25</li>
              <li>Momentum Pack: €200.00 / £151.38 / $364.50</li>
              <li>Elite Performance: €300.00 / £227.07 / $546.75</li>
            </ul>
            <p className="mt-2">Note: Exchange rates are determined by your bank or payment provider if your account currency differs from the transaction currency.</p>
          </div>
          <p><strong>8.3. Price Changes.</strong> We reserve the right to adjust Token package prices or the Token cost of specific Courses at any time. Such changes will not affect Tokens already purchased or Courses already ordered.</p>
        </div>
      </Card>

      {/* Cancellation and Refunds */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">9. Cancellation and Refunds</h2>
        <div className="space-y-3 opacity-90 text-sm">
          <p><strong>9.1. Digital Goods Exemption.</strong> By purchasing Tokens and subsequently exchanging them for a Course (digital content), you acknowledge that the Service begins immediately. Under the Consumer Contracts Regulations 2013 and Consumer Rights Act 2015, you consent to the immediate performance of the contract and acknowledge that you thereby lose your right of withdrawal (cooling-off period) once the content has been made available for download or sent to your email.</p>
          <p><strong>9.2. Refund of Unused Tokens.</strong></p>
          <ul className="list-disc pl-5 space-y-1 ml-4">
            <li>Refunds for unused Token packages may be requested within 14 days of the original transaction date.</li>
            <li>If any Tokens from a package have been used to purchase a Course, the entire package is considered &quot;used&quot; and is non-refundable.</li>
          </ul>
          <p><strong>9.3. Defective Content.</strong> If a file is corrupted or technically defective, please contact support. We will provide a replacement file. If a replacement is not possible, we may refund the Tokens used for that specific file.</p>
        </div>
      </Card>

      {/* Limitation of Liability */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">10. Limitation of Liability</h2>
        <div className="space-y-3 opacity-90 text-sm">
          <p><strong>10.1.</strong> To the fullest extent permitted by law, CHALET AQUARIUS LTD shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation, loss of data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.</p>
          <p><strong>10.2.</strong> Our total liability for any claim arising out of or relating to these Terms or our Services, regardless of the form of the action, is limited to the amount paid by you to us for the Service in the 12 months preceding the claim.</p>
        </div>
      </Card>

      {/* Technical Requirements */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">11. Technical Requirements</h2>
        <p className="opacity-90 text-sm">
          You are responsible for ensuring that you have the necessary hardware (computer, smartphone) and software (PDF reader) to access and view the Courses. We are not liable for incompatibility issues related to your specific device.
        </p>
      </Card>

      {/* Governing Law and Jurisdiction */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">12. Governing Law and Jurisdiction</h2>
        <div className="space-y-3 opacity-90 text-sm">
          <p><strong>12.1.</strong> These Terms are governed by and construed in accordance with the laws of England and Wales.</p>
          <p><strong>12.2.</strong> Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts of London, England.</p>
        </div>
      </Card>

      {/* Contact Information */}
      <Card>
        <h2 className="text-lg font-semibold mb-3">13. Contact Information</h2>
        <div className="space-y-3 opacity-90 text-sm">
          <p>If you have questions regarding these Terms, payment issues, or technical support, please contact us:</p>
          <div className="space-y-1">
            <p><strong>CHALET AQUARIUS LTD</strong></p>
            <p><strong>Address:</strong> 20 Wenlock Road, London, England, N1 7GU</p>
            <p><strong>Email:</strong> info@chaletcoaching.co.uk</p>
            <p><strong>Phone:</strong> +44 7441 392840</p>
          </div>
        </div>
      </Card>
    </main>
  );
}
